//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class authors_has_books
    {
        public Nullable<int> authors_id { get; set; }
        public int books_ISBN_INT { get; set; }
    
        public virtual authors authors { get; set; }
        public virtual books books { get; set; }
    }
}
